development:
  forest_env_secret: 48207e658e23bd0f93c19071f2f3699aca89bf9012954cfd1c91574452cfce99
  forest_auth_secret: 1QDhv3p-w3zKM-YEIn69Mg
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
